services:
  app:
    build:  
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  
volumes:
  node_modules: