import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
      {
          type: 'category',
          label: 'General Information',
          className: 'kwkw',
          items: [{type: 'autogenerated', dirName: 'general-information'}],
          collapsible: true,
          collapsed: true,
      },
      {
          type: 'html',
          value: '<hr class="category-title-hr"/><div class="category-title">Account</div>',
          defaultStyle: true,
      },
      {
          type: 'category',
          label: 'Account',
          items: [{type: 'autogenerated', dirName: 'account'}],
          collapsible: true,
          collapsed: true,
      },
      {
          type: 'category',
          label: 'Market Data',
          items: [{type: 'autogenerated', dirName: 'market-data'}],
          collapsible: true,
          collapsed: true,
      },
      {
          type: 'html',
          value: '<hr class="category-title-hr"/><div class="category-title">Trading</div>',
          defaultStyle: true,
      },
      {
          type: 'category',
          label: 'DCA Bot',
          items: [{type: 'autogenerated', dirName: 'dca-bot'}],
          collapsible: true,
          collapsed: true,
      },
      {
          type: 'category',
          label: 'Grid Bot',
          items: [{type: 'autogenerated', dirName: 'grid-bot'}],
          collapsible: true,
          collapsed: true,
      },
      {
          type: 'category',
          label: 'Smart Trade',
          items: [{type: 'autogenerated', dirName: 'smart-trade'}],
          collapsible: true,
          collapsed: true,
      },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
